services:
  - type: web
    name: smartloan-ai-node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ML_API_URL
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: FORCE_HTTPS_COOKIES
        value: true
      - key: GEMINI_API_KEY
        sync: false